export const QR_PRESETS = [
  {
    id: "classic",
    name: "Classic",
    description: "Dark modules on white — reliable and clean.",
    foregroundColor: "#1a1a2e",
    backgroundColor: "#ffffff",
    dotStyle: "rounded",
    cornerSquareStyle: "extra-rounded",
    cornerDotStyle: "dot",
    errorCorrectionLevel: "H",
    logoBorderColor: "#ffffff",
  },
  {
    id: "midnight",
    name: "Midnight",
    description: "Light modules on a dark background.",
    foregroundColor: "#f4f4f6",
    backgroundColor: "#14141a",
    dotStyle: "rounded",
    cornerSquareStyle: "extra-rounded",
    cornerDotStyle: "dot",
    errorCorrectionLevel: "H",
    logoBorderColor: "#14141a",
  },
  {
    id: "ocean",
    name: "Ocean",
    description: "Cool blues with soft rounded dots.",
    foregroundColor: "#0369a1",
    backgroundColor: "#e0f2fe",
    dotStyle: "dots",
    cornerSquareStyle: "dot",
    cornerDotStyle: "dot",
    errorCorrectionLevel: "H",
    logoBorderColor: "#ffffff",
  },
  {
    id: "forest",
    name: "Forest",
    description: "Deep green on a mint backdrop.",
    foregroundColor: "#166534",
    backgroundColor: "#ecfdf5",
    dotStyle: "extra-rounded",
    cornerSquareStyle: "extra-rounded",
    cornerDotStyle: "dot",
    errorCorrectionLevel: "H",
    logoBorderColor: "#ffffff",
  },
  {
    id: "berry",
    name: "Berry",
    description: "Purple tones with classy rounded shapes.",
    foregroundColor: "#7e22ce",
    backgroundColor: "#faf5ff",
    dotStyle: "classy-rounded",
    cornerSquareStyle: "classy-rounded",
    cornerDotStyle: "dot",
    errorCorrectionLevel: "H",
    logoBorderColor: "#ffffff",
  },
  {
    id: "sunset",
    name: "Sunset",
    description: "Warm orange on a peach background.",
    foregroundColor: "#c2410c",
    backgroundColor: "#fff7ed",
    dotStyle: "rounded",
    cornerSquareStyle: "rounded",
    cornerDotStyle: "dot",
    errorCorrectionLevel: "H",
    logoBorderColor: "#ffffff",
  },
  {
    id: "minimal",
    name: "Minimal",
    description: "Sharp squares and maximum contrast.",
    foregroundColor: "#111111",
    backgroundColor: "#ffffff",
    dotStyle: "square",
    cornerSquareStyle: "square",
    cornerDotStyle: "square",
    errorCorrectionLevel: "H",
    logoBorderColor: "#ffffff",
  },
  {
    id: "slate",
    name: "Slate",
    description: "Muted gray-blue for a subdued look.",
    foregroundColor: "#334155",
    backgroundColor: "#f1f5f9",
    dotStyle: "rounded",
    cornerSquareStyle: "dot",
    cornerDotStyle: "dot",
    errorCorrectionLevel: "H",
    logoBorderColor: "#ffffff",
  },
];

export function getQrPreset(id) {
  return QR_PRESETS.find((p) => p.id === id) || QR_PRESETS[0];
}

export function applyQrPreset(presetId) {
  const preset = getQrPreset(presetId);
  return {
    qrPreset: preset.id,
    foregroundColor: preset.foregroundColor,
    backgroundColor: preset.backgroundColor,
    dotStyle: preset.dotStyle,
    cornerSquareStyle: preset.cornerSquareStyle,
    cornerDotStyle: preset.cornerDotStyle,
    errorCorrectionLevel: preset.errorCorrectionLevel,
    logo: { borderColor: preset.logoBorderColor },
  };
}
